version: "3"

services:
    timescaledb:
        image: timescale/timescaledb:latest-pg16
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: timescaledb
            POSTGRES_PASSWORD: password
        volumes:
            - /data/timescaledb:/var/lib/postgresql/data
